### ISSUE TITLE
Why na value filled with 12?

### ISSUE THREAD

**Issue by JaysonsdLin** [zangzelin/thyroid-project#1]
In command line . Why args '--fillna' was set to 12.0? 
`python main.py --lr 0.002 --l2 0.05 --epochs 100 --alpha 1.6 --batch_size 128 --seed 1 --device cuda --verbose 0 --plot 1 --fillna 12.0 --stan_feature 0 --protein_list_input P02765 P04083 O00339 P58546 O75347 P04216 P02751 P83731 P00568 P78527 P04792 P57737 P42224 P27797 Q9HAT2 P30086 O14964 P10909 P17931 --use_wandb 1`

**Comment by zangzelin** [comment]
Hi,
Please check page 14 of our paper. "Considering that most missing values occurred when the protein content was below the detection threshold, imputation was performed by ﬁlling in all the missing values with [D_{min}], where D_{min} was the minimum of all available features values in the discovery set, and [·] is the ceiling operator. The minimum value was 12 for the discovery set and all the test sets used."
the link of our paper: https://www.nature.com/articles/s41421-022-00442-x
